#!/usr/bin/env python3
"""
PolarCalib.py - Camera calibration from polarization PNM frames + Doosan robot poses.

Each frame* directory contains:
  - colorFrame_0_*.pnm  : raw Bayer-polarization images (same robot pose)
  - robot_pose.csv      : one-row CSV with J1..J6, X,Y,Z,Rx,Ry,Rz
                          IMPORTANT – Doosan H2515 / CS-01 controller encodes TCP
                          orientation as ZYZ Euler angles (degrees), NOT roll-pitch-yaw:
                            Rx → 1st Z rotation (rz1)
                            Ry → Y  rotation    (ry)
                            Rz → 2nd Z rotation (rz2)
                          X,Y,Z translation is in millimetres.
  - camera.csv          : timestamp / frameID table
  - info.json           : capture settings

Images are debayered via readPolarPNMToRGBALive() (4 polarization channels).
The mean of those channels is used as grayscale for chessboard corner detection.
"""

import sys
import os
import glob
import csv

import cv2
import numpy as np

# --- locate readData.py -------------------------------------------------------
_READ_DATA_DIR = '/home/ammar/Documents/Programming/magician_vision_classifier'
if _READ_DATA_DIR not in sys.path:
    sys.path.insert(0, _READ_DATA_DIR)
from readData import readPolarPNMToRGBALive

# --- calibration board parameters --------------------------------------------
BOARD_W   = 9    # inner corners along width
BOARD_H   = 6    # inner corners along height
BOARD_DIM = 11.5   # physical square size in mm
CROP      = 0.5  # alpha for getOptimalNewCameraMatrix (0=tight, 1=all pixels)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

def resize_to_fit_screen(img, max_w=1280, max_h=720, only_shrink=True):
    h, w = img.shape[:2]
    scale = min(max_w / float(w), max_h / float(h))
    if only_shrink and scale >= 1.0:
        return img, 1.0
    nw = max(1, int(round(w * scale)))
    nh = max(1, int(round(h * scale)))
    interp = cv2.INTER_AREA if scale < 1.0 else cv2.INTER_LINEAR
    return cv2.resize(img, (nw, nh), interpolation=interp), scale


def polar_rgba_to_gray(rgba):
    """Average all 4 polarization channels into a single uint8 grayscale image."""
    return np.mean(rgba.astype(np.float32), axis=2).astype(np.uint8)


def load_robot_pose(csv_path):
    """
    Parse robot_pose.csv (single data row).
    Columns: J1,J2,J3,J4,J5,J6,X,Y,Z,Rx,Ry,Rz

    IMPORTANT – Doosan H2515 / CS-01 controller:
      X,Y,Z  : TCP position in millimetres
      Rx,Ry,Rz : ZYZ Euler angles in degrees (NOT roll-pitch-yaw)
                 Rx = rz1 (first  Z), Ry = ry (Y), Rz = rz2 (second Z)

    Returns a dict with float values keyed by the CSV column names.
    """
    with open(csv_path, newline='') as f:
        reader = csv.DictReader(f)
        row = next(reader)
    return {k.strip(): float(v) for k, v in row.items()}


def load_camera_csv(csv_path):
    """
    Parse camera.csv (timestamp / frameID table).
    Returns list of dicts.
    """
    entries = []
    with open(csv_path, newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            entries.append({k.strip(): v.strip() for k, v in row.items()})
    return entries


def save_stereolabs_calib(out_path, width, height, intrinsic_matrix, dist_coeffs,
                          camera_id=0, camera_no=0, date="", description="",
                          scale_unit=1.0,
                          comment_camera="Polarization Camera",
                          comment_source="Generated by PolarCalib.py"):
    I = np.asarray(intrinsic_matrix, dtype=float).reshape(3, 3)
    D = np.asarray(dist_coeffs, dtype=float).reshape(-1)
    if D.size < 5:
        D = np.pad(D, (0, 5 - D.size), mode="constant")
    D = D[:5]

    lines = [
        f"%Calibration File v 1.0.3 - Matlab Load() compatible, "
        f"https://support.stereolabs.com/hc/en-us/articles/360007497173-What-is-the-calibration-file- "
        f"Scale Unit: {scale_unit}  - {comment_camera} - {comment_source}",
        f"%CameraID={camera_id}",
        f"%CameraNo={camera_no}",
        "%Date=" + (date or ""),
        "%Width", str(int(width)),
        "%Height", str(int(height)),
        "%Description=" + (description or ""),
        "%Intrinsics I[1,1], I[1,2], I[1,3], I[2,1], I[2,2], I[2,3], I[3,1], I[3,2] I[3,3]",
        "%I",
    ]
    for r in range(3):
        for c in range(3):
            lines.append(f"{I[r,c]:.8f}")
    lines += ["%Distortion D[1], D[2], D[3], D[4] D[5]", "%D"]
    for v in D:
        lines.append(f"{v:.8f}")
    lines += [
        "%Translation T.X, T.Y, T.Z", "%T", "0", "0", "0",
        "%Rotation Vector (Rodrigues) R.X, R.Y, R.Z", "%R", "0", "0", "0",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# -----------------------------------------------------------------------------
# Core calibration logic
# -----------------------------------------------------------------------------

def collect_calibration_views(base_dir, board_w, board_h, board_dim, show=True):
    """
    Walk every frame* directory, debayer PNM images, detect chessboard corners.

    For each directory the function tries every PNM until a clean detection is
    found (or all are exhausted).  The associated robot pose is stored with the
    successful view.

    Returns
    -------
    opts       : list of object-point arrays (3-D world corners)
    ipts       : list of image-point arrays (2-D detected corners)
    image_size : (width, height) of the calibration images
    views      : list of dicts, one per successful detection:
                   { 'frame_dir', 'pnm_file', 'robot_pose', 'camera_csv',
                     'gray_image', 'corners' }
    """
    frame_dirs = sorted(
        glob.glob(os.path.join(base_dir, 'frame*')),
        key=lambda p: int(os.path.basename(p).replace('frame', ''))
    )
    if not frame_dirs:
        print("No frame* directories found in", base_dir)
        sys.exit(1)

    objp = np.zeros((board_h * board_w, 3), np.float32)
    objp[:, :2] = (
        np.mgrid[0:board_w * board_dim:board_dim,
                 0:board_h * board_dim:board_dim]
        .T.reshape(-1, 2)
    )

    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1)

    opts   = []
    ipts   = []
    views  = []
    image_size = None

    for frame_dir in frame_dirs:
        frame_name = os.path.basename(frame_dir)
        print(f"\n[{frame_name}] scanning {frame_dir}")

        # --- robot pose ---
        pose_csv = os.path.join(frame_dir, 'robot_pose.csv')
        robot_pose = load_robot_pose(pose_csv) if os.path.isfile(pose_csv) else {}
        if robot_pose:
            # Rx/Ry/Rz are ZYZ Euler angles (degrees), not RPY — see load_robot_pose()
            print(f"  Robot TCP  X={robot_pose.get('X'):.2f}mm  Y={robot_pose.get('Y'):.2f}mm"
                  f"  Z={robot_pose.get('Z'):.2f}mm  "
                  f"Rx(rz1)={robot_pose.get('Rx'):.2f}°  Ry(ry)={robot_pose.get('Ry'):.2f}°"
                  f"  Rz(rz2)={robot_pose.get('Rz'):.2f}°")
            print(f"  Joints     J1={robot_pose.get('J1'):.2f}  J2={robot_pose.get('J2'):.2f}"
                  f"  J3={robot_pose.get('J3'):.2f}  J4={robot_pose.get('J4'):.2f}"
                  f"  J5={robot_pose.get('J5'):.2f}  J6={robot_pose.get('J6'):.2f}")

        # --- camera timestamps ---
        cam_csv = os.path.join(frame_dir, 'camera.csv')
        cam_entries = load_camera_csv(cam_csv) if os.path.isfile(cam_csv) else []

        # --- try each PNM until corners are found ---
        pnm_files = sorted(glob.glob(os.path.join(frame_dir, 'colorFrame_0_*.pnm')))
        if not pnm_files:
            print(f"  WARNING: no PNM files in {frame_dir}, skipping")
            continue

        found_view = False
        for pnm_path in pnm_files:
            raw = cv2.imread(pnm_path, cv2.IMREAD_UNCHANGED)
            if raw is None:
                continue

            rgba  = readPolarPNMToRGBALive(raw)
            gray  = polar_rgba_to_gray(rgba)

            found, corners = cv2.findChessboardCorners(
                gray, (board_w, board_h),
                cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_NORMALIZE_IMAGE
            )

            if found:
                cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)

                opts.append(objp)
                ipts.append(corners)
                image_size = (gray.shape[1], gray.shape[0])

                # build a colour display image from polarization channels
                display_bgr = cv2.merge([
                    rgba[:, :, 0],   # 0°  -> B
                    rgba[:, :, 1],   # 45° -> G
                    rgba[:, :, 2],   # 90° -> R
                ])
                cv2.drawChessboardCorners(display_bgr, (board_w, board_h), corners, found)

                views.append({
                    'frame_dir':   frame_dir,
                    'pnm_file':    pnm_path,
                    'robot_pose':  robot_pose,
                    'camera_csv':  cam_entries,
                    'gray_image':  gray,
                    'corners':     corners,
                })

                print(f"  OK  corners found in {os.path.basename(pnm_path)}")

                if show:
                    thumb, _ = resize_to_fit_screen(display_bgr, 1600, 900)
                    cv2.imshow("Chessboard", thumb)
                    cv2.waitKey(300)

                found_view = True
                break   # one good view per pose is enough

        if not found_view:
            print(f"  SKIP  no chessboard corners found in any PNM of {frame_name}")

    if show:
        cv2.destroyAllWindows()

    return opts, ipts, image_size, views


def run_calibration(base_dir=BASE_DIR, board_w=BOARD_W, board_h=BOARD_H,
                    board_dim=BOARD_DIM, show=True):

    print("=" * 60)
    print("Step 1 – collecting calibration views from frame* dirs")
    print("=" * 60)

    opts, ipts, image_size, views = collect_calibration_views(
        base_dir, board_w, board_h, board_dim, show=show
    )

    if len(opts) < 4:
        print(f"\nERROR: Only {len(opts)} valid views found. Need at least 4.")
        sys.exit(1)

    print(f"\nCollected {len(opts)} views for calibration.")

    # --- print collected pose table ------------------------------------------
    print("\nView summary:")
    print(f"  {'Frame dir':<20}  {'PNM file':<30}  {'X':>8}  {'Y':>8}  {'Z':>8}")
    for v in views:
        p = v['robot_pose']
        print(f"  {os.path.basename(v['frame_dir']):<20}  "
              f"{os.path.basename(v['pnm_file']):<30}  "
              f"{p.get('X', float('nan')):>8.2f}  "
              f"{p.get('Y', float('nan')):>8.2f}  "
              f"{p.get('Z', float('nan')):>8.2f}")

    # --- calibrate -----------------------------------------------------------
    print("\n" + "=" * 60)
    print("Step 2 – running cv2.calibrateCamera")
    print("=" * 60)

    w, h = image_size
    ret, K, dist, rvecs, tvecs = cv2.calibrateCamera(
        opts, ipts, (w, h), None, None
    )

    print(f"\nRMS reprojection error: {ret:.4f} px")
    print(f"\nIntrinsic matrix K:\n{K}")
    print(f"\nDistortion coefficients:\n{dist.ravel()}")
    print(f"\n  fX={K[0,0]:.4f}  fY={K[1,1]:.4f}  cX={K[0,2]:.4f}  cY={K[1,2]:.4f}")

    # per-view reprojection error
    tot_error = 0.0
    for i in range(len(opts)):
        proj, _ = cv2.projectPoints(opts[i], rvecs[i], tvecs[i], K, dist)
        tot_error += cv2.norm(ipts[i], proj, cv2.NORM_L2) / len(proj)
    print(f"Mean per-view reprojection error: {tot_error / len(opts):.4f} px")

    # --- save results --------------------------------------------------------
    npz_path   = os.path.join(base_dir, 'calibration_data.npz')
    calib_path = os.path.join(base_dir, 'last.calib')

    np.savez(npz_path, intrinsic_matrix=K, distCoeff=dist,
             rvecs=np.array(rvecs), tvecs=np.array(tvecs),
             image_size=np.array([w, h]))
    print(f"\nSaved NumPy calibration to {npz_path}")

    save_stereolabs_calib(
        out_path=calib_path,
        width=w, height=h,
        intrinsic_matrix=K,
        dist_coeffs=dist,
        description="Polarization camera calibration (polar PNM frames)"
    )
    print(f"Saved Stereolabs-style calibration to {calib_path}")

    # --- save per-view pose CSV ----------------------------------------------
    poses_path = os.path.join(base_dir, 'calibration_poses.csv')
    # Rx/Ry/Rz = ZYZ Euler angles (deg), NOT RPY — Doosan H2515/CS-01 convention
    pose_keys  = ['J1','J2','J3','J4','J5','J6','X','Y','Z','Rx','Ry','Rz']
    with open(poses_path, 'w', newline='') as f:
        writer = csv.writer(f)
        header = ['frame_dir', 'pnm_file',
                  'rvec_x','rvec_y','rvec_z',
                  'tvec_x','tvec_y','tvec_z'] + pose_keys
        writer.writerow(header)
        for i, v in enumerate(views):
            rv = rvecs[i].ravel()
            tv = tvecs[i].ravel()
            rp = v['robot_pose']
            row = (
                [os.path.basename(v['frame_dir']),
                 os.path.basename(v['pnm_file']),
                 rv[0], rv[1], rv[2],
                 tv[0], tv[1], tv[2]]
                + [rp.get(k, '') for k in pose_keys]
            )
            writer.writerow(row)
    print(f"Saved per-view poses to {poses_path}")

    # --- hand-eye calibration ------------------------------------------------
    print("\n" + "=" * 60)
    print("Step 3 – hand-eye calibration (eye-in-hand)")
    print("=" * 60)

    R_gripper2base = []
    t_gripper2base = []
    R_target2cam   = []
    t_target2cam   = []

    # only views that have a complete robot pose can contribute to hand-eye
    he_indices = [i for i, v in enumerate(views) if v['robot_pose']]
    if len(he_indices) < 3:
        print(f"  WARNING: only {len(he_indices)} views have robot pose data; "
              "skipping hand-eye calibration.")
        return K, dist, rvecs, tvecs, views, None, None

    print(f"  Using {len(he_indices)} of {len(views)} views "
          f"(skipped {len(views)-len(he_indices)} without robot pose).")

    for i in he_indices:
        v = views[i]
        rp = v['robot_pose']

        # Doosan H2515/CS-01 reports TCP orientation as ZYZ Euler angles in degrees.
        # The column names Rx/Ry/Rz are misleading — they are NOT roll-pitch-yaw:
        #   Rx → rz1  (first  rotation, about Z)
        #   Ry → ry   (second rotation, about Y)
        #   Rz → rz2  (third  rotation, about Z)
        # Rotation matrix = Rz(rz1) @ Ry(ry) @ Rz(rz2)
        rz1 = np.radians(rp['Rx'])  # 1st Z angle
        ry  = np.radians(rp['Ry'])  # Y   angle
        rz2 = np.radians(rp['Rz'])  # 2nd Z angle

        cz1, sz1 = np.cos(rz1), np.sin(rz1)
        cy,  sy  = np.cos(ry),  np.sin(ry)
        cz2, sz2 = np.cos(rz2), np.sin(rz2)

        Rz1 = np.array([[ cz1, -sz1, 0],
                        [ sz1,  cz1, 0],
                        [   0,    0, 1]], dtype=np.float64)
        Ry_ = np.array([[ cy,  0, sy],
                        [  0,  1,  0],
                        [-sy,  0, cy]], dtype=np.float64)
        Rz2 = np.array([[ cz2, -sz2, 0],
                        [ sz2,  cz2, 0],
                        [   0,    0, 1]], dtype=np.float64)

        R_g2b = Rz1 @ Ry_ @ Rz2
        t_g2b = np.array([[rp['X']], [rp['Y']], [rp['Z']]], dtype=np.float64)

        R_gripper2base.append(R_g2b)
        t_gripper2base.append(t_g2b)

        # Camera-to-pattern transform from calibrateCamera
        R_t2c, _ = cv2.Rodrigues(rvecs[i])
        t_t2c    = tvecs[i].reshape(3, 1).astype(np.float64)

        R_target2cam.append(R_t2c)
        t_target2cam.append(t_t2c)

    R_cam2gripper, t_cam2gripper = cv2.calibrateHandEye(
        R_gripper2base, t_gripper2base,
        R_target2cam,   t_target2cam,
        method=cv2.CALIB_HAND_EYE_TSAI,
    )

    print(f"\nR_cam2gripper:\n{R_cam2gripper}")
    print(f"\nt_cam2gripper (mm):\n{t_cam2gripper.ravel()}")

    hand_eye_path = os.path.join(base_dir, 'hand_eye.npz')
    np.savez(hand_eye_path,
             R_cam2gripper=R_cam2gripper,
             t_cam2gripper=t_cam2gripper)
    print(f"\nSaved hand-eye result to {hand_eye_path}")

    # --- show undistorted views ----------------------------------------------
    if show:
        print("\nStep 4 – displaying undistorted views (press any key to advance)")
        newK, roi = cv2.getOptimalNewCameraMatrix(K, dist, (w, h), alpha=CROP,
                                                   centerPrincipalPoint=1)
        mapx, mapy = cv2.initUndistortRectifyMap(K, dist, None, newK, (w, h),
                                                  cv2.CV_32FC1)
        for v in views:
            raw  = cv2.imread(v['pnm_file'], cv2.IMREAD_UNCHANGED)
            rgba = readPolarPNMToRGBALive(raw)
            bgr  = cv2.merge([rgba[:,:,0], rgba[:,:,1], rgba[:,:,2]])
            dst  = cv2.remap(bgr, mapx, mapy, cv2.INTER_LINEAR)
            thumb, _ = resize_to_fit_screen(dst, 1600, 900)
            cv2.imshow('Undistorted', thumb)
            if cv2.waitKey(0) == 27:
                break
        cv2.destroyAllWindows()

    return K, dist, rvecs, tvecs, views, R_cam2gripper, t_cam2gripper


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------

if __name__ == '__main__':
    run_calibration(
        base_dir  = BASE_DIR,
        board_w   = BOARD_W,
        board_h   = BOARD_H,
        board_dim = BOARD_DIM,
        show      = True,
    )
